LARGE_INVESTIGATION_POST = {
    "publications": [
        {
            "fullReference": "string",
            "repository": "string",
            "url": "string",
            "doi": "string",
            "repositoryId": "string",
        },
    ],
    "fileSize": 1,
    "studyInvestigations": [{"study": 1}],
    "title": "string",
    "type": 1,
    "investigationFacilityCycles": [{"facilityCycle": 1}],
    "investigationUsers": [{"role": "string", "user": 1}],
    "summary": "string",
    "name": "string",
    "doi": "string",
    "visitId": "test large",
    "facility": 1,
    "datasets": [
        {
            "complete": False,
            "type": 1,
            "fileCount": 0,
            "parameters": [
                {
                    "stringValue": "string",
                    "dateTimeValue": "2019-01-04 01:01:01+00:00",
                    "numericValue": 0,
                    "dataset": 1,
                    "rangeBottom": 0,
                    "type": 3,
                    "rangeTop": 0,
                    "error": 0,
                },
            ],
            "startDate": "2019-01-04 01:01:01+00:00",
            "doi": "string",
            "name": "string",
            "datasetTechniques": [{"technique": 1}],
            "fileSize": 0,
            "description": "string",
            "endDate": "2019-01-04 01:01:01+00:00",
            "sample": 1,
            "location": "string",
        },
    ],
    "fileCount": 0,
    "samples": [
        {
            "type": 1,
            "pid": "string",
            "parameters": [
                {
                    "stringValue": "string",
                    "dateTimeValue": "2019-01-04 01:01:01+00:00",
                    "numericValue": 0,
                    "rangeBottom": 0,
                    "type": 3,
                    "rangeTop": 0,
                    "error": 0,
                    "sample": 0,
                },
            ],
            "name": "string",
        },
    ],
    "endDate": "2019-01-04 01:01:01+00:00",
}
