version: 2
updates:

  # Maintain Dockerfile dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: daily
      time: "08:00"
      timezone: "Europe/London"
    ignore:
      - dependency-name: "python"
        update-types: ["version-update:semver-major", "version-update:semver-minor"]

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates every week
      interval: "weekly"
