name: Release Build
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Release Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          fetch-depth: 0
          token: ${{ secrets.ADMIN_PAT }}

      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@3abfb7ac216b9ad439de24fda60eca84038e850e # v8.0.8
        with:
          github_token: ${{ secrets.ADMIN_PAT }}
