name: Release Build
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Release Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          fetch-depth: 0
          token: ${{ secrets.ADMIN_PAT }}

      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@d38d71ef2ae2b3c34066557ddb822385c1730c7f # v8.3.0
        with:
          github_token: ${{ secrets.ADMIN_PAT }}
