name: Release Build
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Release Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab # v3.5.2
        with:
          fetch-depth: 0
          token: ${{ secrets.ADMIN_PAT }}

      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@3c7db14e7c1898bd4c1e748b3fa20a2d5eef3abe # v8.0.7
        with:
          github_token: ${{ secrets.ADMIN_PAT }}
